### ISSUE TITLE
(400) Bad Request

### ISSUE THREAD

**Issue by BryRamCam1** [microsoft/manageability-toolkits#2]
Hello Guys, 

We are from SWO cloud support, and one of our customers is trying to use this code to generate the alerts, however is getting  The remote server returned an error: (400) Bad Request when creating the alert 1 of 38 'High CPU Usage', can you please check and let me know if there is any issue here?
![400badrequest](https://user-images.githubusercontent.com/53265490/61798095-ef92c480-ade5-11e9-89fd-c04c119d7097.png)

**Comment by msmacarlso** [comment]
There was a change made to the API for new workspaces created beyond a certain date. I am working on getting a fix out ASAP today. I will update you when it’s completed. It will require the new AZ modules FYI.

Thanks,
Matt Carlson

**Comment by msmacarlso** [comment]
The code has been updated with a fix. Please note that this involved moving to the new Az module. This is a new dependency. AzureRm is no longer required. This allows us to use Azure PowerShell without relying on any API calls for alert creation.
