### ISSUE TITLE
Getting errors when i run PS script .\New-CoreAlerts.ps1

### ISSUE THREAD

**Issue by Nighteyes999** [microsoft/manageability-toolkits#4]
Hi,

I followed your steps until the part i have to run the PS script. 

.\New-CoreAlerts.ps1 

But i am getting these errors : 

***

At C:\Users\......r\New-CoreAlerts.ps1:148 char:19
+               Sign&nbsp;up
+                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:......\New-CoreAlerts.ps1:175 char:190

***
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At C:\Users\.....\New-CoreAlerts.ps1:190 char:255

******

The errors seem to be related to symbols like "&" and "<" not being allowed. Do you know how i can have this fixed?

**Comment by msmacarlso** [comment]
Are you just running ".\New-CoreAlerts.ps1" or are you passing any parameters? Do the values you are inputting into the script, through parameters or guided questions, contain any of these characters mentioned in the error? If not, can you confirm the encoding type of the script and json file (eg UTF-8, Unicode)? If you can provide the exact command you ran that would be preferable, but please do generalize any subscription specific information. If there command contains any of those characters I would want to see where they are though.

**Comment by Nighteyes999** [comment]
Hi Matt.

Thanks for replying. 

I ran the script without parameters. that is _(initially tried with params but it showed me errors so i ran without param)_ :
.\New-CoreAlerts.ps1

In your guide (under Deployment Steps) it states that I run the script without paramters and it should prompt me for the required parameters. But i got those errors related to "&" and "<" (attaching the error messages in a text file).

I downloaded DefaultAlertConfig.json & New-CoreAlerts.ps1, directly from github.I didn't make any changes to these files. 

Also attached a screenshot of error message i got. Do take a look and let me know if there is anything i need to do.
[errormessage.txt](https://github.com/microsoft/manageability-toolkits/files/3904514/errormessage.txt)

![Capture-error_script](https://user-images.githubusercontent.com/57426771/69857973-fc5f8180-12cb-11ea-9710-2d7c08697bfb.PNG)

**Comment by msmacarlso** [comment]
Can you please try downloading the files again, perhaps as a zip file and then extract it?

The text you listed in your original post, "Sign&nbsp;up" and the tilda, do not appear anywhere in the script. I suspect this has something to do with the way the file was downloaded.

Here's a screen grab of the ideal way to download the script:
![image](https://user-images.githubusercontent.com/25779772/69904161-35453800-1358-11ea-8b34-18cde7479c94.png)

**Comment by Nighteyes999** [comment]
Hi Matt,

Thank you. I downloaded the script using the 'Download ZIP' method you provided and it works!

I guess the culprit was the way i downloaded the individual JSON and PS1 files in Google Chrome (right click- Save as). 

The script is now running and everything looks great! Thank you again!
